[package]
name = "ubiquity"
version = "0.1.0"
authors = ["Alex Stokes <r.alex.stokes@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.2.0"
itertools = "0.8.0"
linefeed = "0.5.4"
ansi_term = "0.11.0"
